# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1szebgcwJNkl_4WLG40nzcjW7tnRz6LF7
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set plotting style for better aesthetics
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (10, 6)

"""## Data Loading and Initial Inspection"""

df_fund_master = pd.read_csv('/content/01_fund_master.csv')
display(df_fund_master.head())

df_nav_history = pd.read_csv('/content/02_nav_history.csv')
display(df_nav_history.head())

df_aum_by_fund_house = pd.read_csv('/content/03_aum_by_fund_house.csv')
display(df_aum_by_fund_house.head())

df_monthly_sip_inflows = pd.read_csv('/content/04_monthly_sip_inflows.csv')
display(df_monthly_sip_inflows.head())

df_category_inflows = pd.read_csv('/content/05_category_inflows.csv')
display(df_category_inflows.head())

df_industry_folio_count = pd.read_csv('/content/06_industry_folio_count.csv')
display(df_industry_folio_count.head())

df_scheme_performance = pd.read_csv('/content/07_scheme_performance.csv')
display(df_scheme_performance.head())

df_investor_transactions = pd.read_csv('/content/08_investor_transactions.csv')
display(df_investor_transactions.head())

df_portfolio_holdings = pd.read_csv('/content/09_portfolio_holdings.csv')
display(df_portfolio_holdings.head())

df_benchmark_indices = pd.read_csv('/content/10_benchmark_indices.csv')
display(df_benchmark_indices.head())

"""## Insight 1: Top 10 Fund Houses by AUM"""

# Ensure 'aum_crore' is numeric, coercing errors to NaN
df_aum_by_fund_house['aum_crore'] = pd.to_numeric(df_aum_by_fund_house['aum_crore'], errors='coerce')

# Drop rows where 'aum_crore' is NaN after conversion
df_aum_by_fund_house.dropna(subset=['aum_crore'], inplace=True)

# Group by 'Fund House' and sum 'aum_crore' to get total AUM for each fund house
top_fund_houses = df_aum_by_fund_house.groupby('fund_house')['aum_crore'].sum().nlargest(10).sort_values(ascending=False)

plt.figure(figsize=(12, 7))
sns.barplot(x=top_fund_houses.index, y=top_fund_houses.values, palette='viridis')
plt.title('Top 10 Fund Houses by Total AUM (Cr)')
plt.xlabel('Fund House')
plt.ylabel('Total AUM (Cr)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""This bar chart visualizes the top 10 fund houses based on their total Assets Under Management (AUM) in Crores. It helps to identify the largest players in the mutual fund industry, indicating market dominance and investor trust in these specific fund houses.

## Insight 3: Category-wise Net Inflows
"""

# Group by 'category' and sum 'net_inflow_crore'
category_inflows_sum = df_category_inflows.groupby('category')['net_inflow_crore'].sum().nlargest(10).sort_values(ascending=False)

plt.figure(figsize=(12, 7))
sns.barplot(x=category_inflows_sum.index, y=category_inflows_sum.values, palette='plasma')
plt.title('Top 10 Fund Categories by Total Net Inflow (Cr)')
plt.xlabel('Fund Category')
plt.ylabel('Total Net Inflow (Cr)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""This bar chart displays the total net inflows into different mutual fund categories. It highlights the categories that are most popular among investors, which can indicate current market trends, investor risk appetite, or specific investment themes dominating the market.

## Insight 4: Top 10 Schemes by AUM
"""

# Ensure 'aum_crore' is numeric, coercing errors to NaN
df_scheme_performance['aum_crore'] = pd.to_numeric(df_scheme_performance['aum_crore'], errors='coerce')

# Drop rows where 'aum_crore' is NaN after conversion
df_scheme_performance.dropna(subset=['aum_crore'], inplace=True)

# Get top 10 schemes by AUM
top_schemes_aum = df_scheme_performance.groupby('scheme_name')['aum_crore'].sum().nlargest(10).sort_values(ascending=False)

plt.figure(figsize=(12, 7))
sns.barplot(x=top_schemes_aum.index, y=top_schemes_aum.values, palette='coolwarm')
plt.title('Top 10 Schemes by Total AUM (Cr)')
plt.xlabel('Scheme Name')
plt.ylabel('Total AUM (Cr)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""This bar chart displays the top 10 individual mutual fund schemes based on their total Assets Under Management. This insight can help pinpoint specific schemes that have garnered significant investor capital, often indicating strong market performance, investor confidence, or effective marketing by the fund house.

## Insight 5: Growth in Equity Folios Over Time
"""

# Convert 'month' column to datetime objects
df_industry_folio_count['month'] = pd.to_datetime(df_industry_folio_count['month'])

# Plotting the growth in equity folios
plt.figure(figsize=(14, 7))
sns.lineplot(x='month', y='equity_folios_crore', data=df_industry_folio_count, marker='o')
plt.title('Growth of Equity Folios (Crore) Over Time')
plt.xlabel('Month')
plt.ylabel('Equity Folios (Crore)')
plt.grid(True)
plt.tight_layout()
plt.show()

"""This line chart visualizes the growth in the number of equity folios over time. An increasing trend in equity folios signifies growing investor confidence and participation in the equity market through mutual funds, reflecting broader economic sentiment and investment trends.

## Insight 6: Top 10 Schemes by 1-Year Return
"""

# Ensure 'return_1yr_pct' is numeric, coercing errors to NaN
df_scheme_performance['return_1yr_pct'] = pd.to_numeric(df_scheme_performance['return_1yr_pct'], errors='coerce')

# Drop rows where 'return_1yr_pct' is NaN after conversion
df_scheme_performance.dropna(subset=['return_1yr_pct'], inplace=True)

# Get top 10 schemes by 1-year return
top_schemes_return = df_scheme_performance.nlargest(10, 'return_1yr_pct')

plt.figure(figsize=(12, 7))
sns.barplot(x='scheme_name', y='return_1yr_pct', data=top_schemes_return, palette='magma')
plt.title('Top 10 Schemes by 1-Year Return (%)')
plt.xlabel('Scheme Name')
plt.ylabel('1-Year Return (%)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""This bar chart highlights the top 10 mutual fund schemes based on their 1-year returns. This insight is crucial for investors looking for funds with strong short-term performance and can indicate market trends or the effectiveness of a fund manager's strategy in the recent past.

## Insight 7: Top Fund Managers by Number of Schemes Managed
"""

# Count the number of schemes managed by each fund manager
manager_scheme_count = df_fund_master['fund_manager'].value_counts().nlargest(10)

plt.figure(figsize=(12, 7))
sns.barplot(x=manager_scheme_count.index, y=manager_scheme_count.values, palette='cool_r')
plt.title('Top 10 Fund Managers by Number of Schemes Managed')
plt.xlabel('Fund Manager')
plt.ylabel('Number of Schemes')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""This bar chart showcases the top 10 fund managers based on the number of schemes they actively manage. This insight can indicate key personnel within the mutual fund industry and their level of responsibility or influence across various funds.

## Insight 8: Distribution of Schemes by Risk Grade
"""

# Count the occurrences of each risk grade
risk_grade_distribution = df_scheme_performance['risk_grade'].value_counts()

plt.figure(figsize=(10, 6))
sns.barplot(x=risk_grade_distribution.index, y=risk_grade_distribution.values, palette='RdYlGn')
plt.title('Distribution of Schemes by Risk Grade')
plt.xlabel('Risk Grade')
plt.ylabel('Number of Schemes')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""This bar chart illustrates the distribution of mutual fund schemes across various risk grades. It provides an overview of how many funds fall into each risk category (e.g., Low, Moderate, High), helping investors understand the general risk appetite prevalent in the market and where most investment options are concentrated.

## Insight 9: Top 10 Most Held Stocks Across Portfolios
"""

# Group by 'stock_name' and sum 'weight_pct' to find the overall weight of each stock
top_held_stocks = df_portfolio_holdings.groupby('stock_name')['weight_pct'].sum().nlargest(10).sort_values(ascending=False)

plt.figure(figsize=(12, 7))
sns.barplot(x=top_held_stocks.index, y=top_held_stocks.values, palette='Greens_d')
plt.title('Top 10 Most Held Stocks by Aggregated Weight Across Portfolios')
plt.xlabel('Stock Name')
plt.ylabel('Aggregated Weight (%)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""This bar chart identifies the top 10 stocks that are most frequently or heavily weighted across different mutual fund portfolios. This insight can reveal common investment themes or high-conviction holdings among fund managers, potentially indicating consensus on certain company's future prospects.

## Insight 10: Total Investment Amount by Age Group and Gender
"""

# Group by 'age_group' and 'gender' and sum 'amount_inr'
investment_by_demographics = df_investor_transactions.groupby(['age_group', 'gender'])['amount_inr'].sum().unstack()

investment_by_demographics.plot(kind='bar', figsize=(14, 7), colormap='Paired')
plt.title('Total Investment Amount (INR) by Age Group and Gender')
plt.xlabel('Age Group')
plt.ylabel('Total Investment Amount (INR)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""This grouped bar chart provides an overview of total investment amounts segmented by age group and gender. This insight can help understand the investment behavior of different demographic segments, potentially revealing which groups are more active or invest larger sums, which is valuable for targeted marketing and product development.

## Insight 2: Monthly SIP Inflow Trends
"""

# Convert 'month' column to datetime objects for proper plotting
df_monthly_sip_inflows['month'] = pd.to_datetime(df_monthly_sip_inflows['month'])

# Plotting the monthly SIP inflows
plt.figure(figsize=(14, 7))
sns.lineplot(x='month', y='sip_inflow_crore', data=df_monthly_sip_inflows, marker='o')
plt.title('Monthly SIP Inflows (Cr)')
plt.xlabel('Month')
plt.ylabel('SIP Inflow (Cr)')
plt.grid(True)
plt.tight_layout()
plt.show()

"""This line plot illustrates the trend of monthly SIP inflows over time. It provides a clear view of the growth or fluctuations in Systematic Investment Plan contributions, reflecting investor sentiment and participation in mutual funds. A consistent upward trend signifies increasing investor confidence and financial discipline."""